name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the download and build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v2

      - name: Test
        run: bazel test --test_output=all $(bazel query //...)
